Added nose task

diff --git a/tekton/tasks.yaml b/tekton/tasks.yaml
--- a/tekton/tasks.yaml
+++ b/tekton/tasks.yaml
@@ -6,6 +6,9 @@
 #   to use to create that container. 
 #
 ---
+###############
+# TASK - echo
+###############
 apiVersion: tekton.dev/v1beta1
 kind: Task
 metadata:
@@ -22,6 +25,9 @@ spec:
       command: [/bin/echo]
       args: ["$(params.message)"]
 ---
+##################
+# TASK - cleanup
+##################
 apiVersion: tekton.dev/v1beta1
 kind: Task
 metadata:
@@ -56,4 +62,42 @@ spec:
           # Delete files and directories starting with .. plus any other character
           rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
         fi
+---
+###############
+# TASK - nose
+###############
+apiVersion: tekton.dev/v1beta1
+kind: Task
+metadata:
+  name: nose
+spec:
+  description: This task will run nosetests on the provided input.
+  workspaces:
+  - name: source
+  params:
+    - name: args
+      description: Arguments to pass to nose
+      type: string
+      default: "-v"
+    - name: database_uri
+      description: Database connection string
+      type: string
+      default: "sqlite:///test.db"
+  steps:
+    - name: nosetests
+      image: python:3.9-slim
+      workingDir: $(workspaces.source.path)
+      env:
+        - name: DATABASE_URI
+          value: $(params.database_uri)
+      script: |
+        #!/bin/bash
+        set -e
 
+        echo "***** Installing dependencies *****"
+        python -m pip install --upgrade pip wheel
+        pip install -qr requirements.txt
+
+        echo "***** Running nosetests with: $(params.args)"
+        nosetests $(params.args)
+  
